export type ContractType = 'hash' | 'earnings' | 'uptime' | 'wear' | 'bots' | 'spend' | 'research' | 'events' | 'regime';

export interface ContractTemplate {
  id: string;
  title: string;
  description: string;
  goalLabel: string;
  icon: string;
  color: string;
  type: ContractType;
  target: number;
  durationTicks: number;
  cashReward: number;
  insightReward: number;
  minPrestige?: number;
  minRigs?: number;
}

export const CONTRACT_TEMPLATES: ContractTemplate[] = [
  {
    id: 'hash_sprint',
    title: 'Hash Rush',
    description: 'Sustain serious hash power for this contract period.',
    goalLabel: 'Maintain 80 GH/s',
    icon: 'speedometer',
    color: '#4A8FE7',
    type: 'hash',
    target: 80,
    durationTicks: 60,
    cashReward: 3000,
    insightReward: 20,
    minRigs: 1,
  },
  {
    id: 'earnings_run',
    title: 'Cash Flow',
    description: 'Generate consistent earnings across all income streams.',
    goalLabel: 'Earn $6,000 total',
    icon: 'trending-up',
    color: '#2DD4A0',
    type: 'earnings',
    target: 6000,
    durationTicks: 50,
    cashReward: 2500,
    insightReward: 15,
  },
  {
    id: 'uptime_master',
    title: 'Iron Uptime',
    description: 'Demonstrate perfect hardware maintenance.',
    goalLabel: 'Keep uptime >90% for 50 ticks',
    icon: 'checkmark-circle',
    color: '#2DD4A0',
    type: 'uptime',
    target: 50,
    durationTicks: 60,
    cashReward: 2500,
    insightReward: 25,
    minRigs: 1,
  },
  {
    id: 'wear_manager',
    title: 'Pristine District',
    description: 'Prove your maintenance operations are world-class.',
    goalLabel: 'Keep wear <20 for 40 ticks',
    icon: 'shield-checkmark',
    color: '#9B7FE8',
    type: 'wear',
    target: 40,
    durationTicks: 50,
    cashReward: 2000,
    insightReward: 12,
    minRigs: 1,
  },
  {
    id: 'bot_operator',
    title: 'Bot Commander',
    description: 'Demonstrate automated trading proficiency.',
    goalLabel: 'Run 2+ bots for 30 ticks',
    icon: 'hardware-chip',
    color: '#F5A623',
    type: 'bots',
    target: 30,
    durationTicks: 40,
    cashReward: 4000,
    insightReward: 30,
  },
  {
    id: 'big_spender',
    title: 'Infrastructure Push',
    description: 'Commit to a major district expansion.',
    goalLabel: 'Spend $12,000 on buildings',
    icon: 'construct',
    color: '#4A8FE7',
    type: 'spend',
    target: 12000,
    durationTicks: 80,
    cashReward: 3500,
    insightReward: 40,
  },
  {
    id: 'hash_elite',
    title: 'Elite Miner',
    description: 'Push your district to elite-tier hash performance.',
    goalLabel: 'Reach 400 GH/s total',
    icon: 'flame',
    color: '#F5A623',
    type: 'hash',
    target: 400,
    durationTicks: 0,
    cashReward: 8000,
    insightReward: 55,
    minRigs: 3,
  },
  {
    id: 'crash_survivor',
    title: 'Bear Warrior',
    description: 'Stay profitable while markets crash around you.',
    goalLabel: 'Earn $3,000 during Crash regime',
    icon: 'trending-down',
    color: '#FF4F5E',
    type: 'regime',
    target: 3000,
    durationTicks: 100,
    cashReward: 6000,
    insightReward: 40,
    minRigs: 2,
  },
  {
    id: 'mania_rider',
    title: 'Bull Runner',
    description: 'Maximize profits when markets are euphoric.',
    goalLabel: 'Earn $12,000 during Mania',
    icon: 'rocket',
    color: '#2DD4A0',
    type: 'regime',
    target: 12000,
    durationTicks: 80,
    cashReward: 7000,
    insightReward: 50,
    minRigs: 2,
  },
  {
    id: 'research_rush',
    title: 'Scholar',
    description: 'Accelerate your research program.',
    goalLabel: 'Unlock 3 research nodes',
    icon: 'flask',
    color: '#9B7FE8',
    type: 'research',
    target: 3,
    durationTicks: 120,
    cashReward: 3000,
    insightReward: 70,
  },
  {
    id: 'event_handler',
    title: 'Crisis Pro',
    description: 'Prove you can handle any incident thrown at you.',
    goalLabel: 'Handle 3 incidents',
    icon: 'alert-circle',
    color: '#FF4F5E',
    type: 'events',
    target: 3,
    durationTicks: 200,
    cashReward: 5000,
    insightReward: 35,
  },
  {
    id: 'asic_operator',
    title: 'ASIC Master',
    description: 'Build a serious ASIC-grade mining operation.',
    goalLabel: 'Have 3 ASIC Blades running',
    icon: 'server',
    color: '#F5A623',
    type: 'hash',
    target: 450,
    durationTicks: 0,
    cashReward: 14000,
    insightReward: 90,
    minPrestige: 0,
    minRigs: 3,
  },
  // ─── Prestige-Gated Contracts ──────────────────────────────────────────────
  {
    id: 'quantum_harvest',
    title: 'Quantum Harvest',
    description: 'Push your quantum-grade infrastructure to peak sustained output.',
    goalLabel: 'Maintain 1000 GH/s',
    icon: 'planet',
    color: '#9B7FE8',
    type: 'hash',
    target: 1000,
    durationTicks: 30,
    cashReward: 20000,
    insightReward: 80,
    minPrestige: 2,
    minRigs: 5,
  },
  {
    id: 'bull_runner_p1',
    title: 'Profit Machine',
    description: 'Generate massive cash flow from your upgraded operation.',
    goalLabel: 'Earn $100,000 total',
    icon: 'trending-up',
    color: '#2DD4A0',
    type: 'earnings',
    target: 100000,
    durationTicks: 80,
    cashReward: 12000,
    insightReward: 60,
    minPrestige: 1,
  },
  {
    id: 'bot_commander_crash',
    title: 'Crisis Automation',
    description: 'Keep your entire bot fleet running through a market crash.',
    goalLabel: 'Run 4 bots during crash for 20 ticks',
    icon: 'hardware-chip',
    color: '#FF4F5E',
    type: 'bots',
    target: 20,
    durationTicks: 100,
    cashReward: 8000,
    insightReward: 50,
    minPrestige: 1,
    minRigs: 3,
  },
  {
    id: 'quantum_arms_race',
    title: 'Quantum Arms Race',
    description: 'Build a fleet of quantum-tier mining rigs.',
    goalLabel: 'Reach 1200 GH/s total',
    icon: 'flash',
    color: '#F5A623',
    type: 'hash',
    target: 1200,
    durationTicks: 0,
    cashReward: 25000,
    insightReward: 100,
    minPrestige: 2,
    minRigs: 5,
  },
  {
    id: 'mania_mogul',
    title: 'Mania Mogul',
    description: 'Extract maximum value when markets go euphoric.',
    goalLabel: 'Earn $50,000 during Mania',
    icon: 'rocket',
    color: '#2DD4A0',
    type: 'regime',
    target: 50000,
    durationTicks: 80,
    cashReward: 15000,
    insightReward: 70,
    minPrestige: 2,
    minRigs: 3,
  },
];

export const CONTRACTS_PER_SLOT = 3;
export const CONTRACT_REFRESH_TICKS = 200;
